use_frameworks!

platform :ios, '11.0'

target 'ChatBotTest_Example' do
  pod 'ChatBotTest', :path => '../'

  target 'ChatBotTest_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
