use_frameworks!

platform :ios, '9.0'

platform :ios, '11.0'

target 'ChatBotTest' do
  pod 'Firebase'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'CountryList'
  pod 'AMKeyboardFrameTracker'
end

target 'ChatBotTest_Example' do
  pod 'ChatBotTest', :path => '../'

  target 'ChatBotTest_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
